POST http://{{host}}/recommendations
Content-Type: application/json

{
    "answers": {
        "Ваш пол": [
            "Мужской"
        ],
        "Сколько Вам полных лет?": [
            "26"
        ],
        "Ваш рост": [
            "183"
        ],
        "Ваш вес": [
            "70"
        ],
        "Есть ли у вас сейчас жалобы?": [
            "Нет"
        ],
        "Укажите свое систолическое (верхнее) давление": [
            "Не знаю"
        ],
        "Отметьте, какие хронические заболевания у вас есть или были": [
            "У меня нет известных мне хроничеких заболеваний"
        ],
        "Какие хронические заболевания есть/были у ваших близких родственников (родители, дети, братья/сестры)": [
            "ничего"
        ],
        "Вы курите?": [
            "Нет"
        ],
        "Употребляете ли Вы алкоголь?": [
            "Нет"
        ],
        "Лежали ли Вы в больнице?": [
            "Нет"
        ],
        "Были ли у Вас какие-либо операции?": [
            "Нет"
        ],
        "Принимаете ли Вы сейчас какие-то лекарства?": [
            "Нет"
        ],
        "Есть ли у Вас аллергия?": [
            "Нет"
        ],
        "Отметьте жалобы общего состояния": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с кожей": [
            "Сухость"
        ],
        "Отметьте жалобы в области головы": [
            "Звон в ушах"
        ],
        "Отметьте жалобы с дыханием": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с сердцем": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с животом": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с половой системой": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с мышцами": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с кровью": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с щитовидкой": [
            "Ничего из вышеперечисленного"
        ],
        "Отметьте жалобы с ментальным здоровьем": [
            "Ничего из вышеперечисленного"
        ],
        "Делали ли Вы прививку от вируса папилломы человека?": [
            "Нет"
        ],
        "Сдавали ли Вы кровь на липидный профиль?": [
            "Нет"
        ],
        "У Вас низкая физическая активность? У Вас сидячий образ жизни?": [
            "Нет"
        ],
        "Ответьте на вопрос от 0 до 5, где: 0-У меня в легких совсем нет мокроты (слизи); 5-Мои легкие наполнены мокротой (слизью)": [
            "NaN"
        ],
        "Ответьте на вопрос от 0 до 5, где: 0-У меня совсем нет ощущения сдавленности в грудной лкетке; 5-У меня очень сильное ощущение сдавленности в грудной клетке": [
            "0"
        ],
        "Сдавали ли Вы анализ кала с использованием гваяковой кислоты или фекального иммунохимического анализа на скрытую кровь?": [
            "Нет"
        ],
        "Оцените качество опросника по 5 бальной шкале": [
            "0"
        ]
    }
}

###

